"""
Django settings for eGov project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv_file(file_path: Path) -> None:
    if not file_path.exists():
        return

    for raw_line in file_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # If env var is missing or empty, load the value from .env.
        existing = os.environ.get(key)
        if existing is None or str(existing).strip() == "":
            os.environ[key] = value


load_dotenv_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a7%d$kk%3a0=0(!^1bt3_n)kfdyiy+w^zda9k!(02gc%b0c-vc'

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.environ.get("DJANGO_DEBUG", "true").strip().lower()
DEBUG = _debug_env not in ("0", "false", "no", "off")

# En développement, accepter n'importe quel Host (accès par IP / nom de machine).
# En production, définir DJANGO_ALLOWED_HOSTS=domaine.com,www.domaine.com
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        
    ]
    _extra_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
    if _extra_hosts:
        ALLOWED_HOSTS.extend(h.strip() for h in _extra_hosts.split(",") if h.strip())

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/login/"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eGov.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eGov.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def db_config(prefix: str, default_name: str) -> dict:
    return {
        "ENGINE": os.environ.get(f"{prefix}_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get(f"{prefix}_NAME", default_name),
        "USER": os.environ.get(f"{prefix}_USER", "postgres"),
        "PASSWORD": os.environ.get(f"{prefix}_PASSWORD", ""),
        "HOST": os.environ.get(f"{prefix}_HOST", "localhost"),
        "PORT": os.environ.get(f"{prefix}_PORT", "5432"),
    }


DATABASES = {
    "default": db_config("DB_DEFAULT", "PARAMETRE"),
    "KINSHASA": db_config("DB_KINSHASA", "KINSHASA"),
    "KONGO_CENTRAL": db_config("DB_KONGO_CENTRAL", "KONGO_CENTRAL"),
    "POLICE": db_config("DB_POLICE", "POLICE"),
    "KWILU": db_config("DB_KWILU", "KWILU"),
    "MAI_NDOMBE": db_config("DB_MAI_NDOMBE", "MAI_NDOMBE"),
    "KWANGO": db_config("DB_KWANGO", "KWANGO"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
